# Generated by Django 5.0.6 on 2024-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликовать блог', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, help_text='Введите содержимое', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(help_text='Введите ссылку', max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Количество просмотров'),
        ),
    ]
